# Generated by Django 5.1 on 2024-08-30 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_n_air', '0003_buy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buy',
            new_name='Buys',
        ),
    ]
