# Generated by Django 5.1 on 2024-08-30 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_n_air', '0004_rename_buy_buys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buys',
            new_name='Buy',
        ),
    ]
