# Generated by Django 5.1 on 2024-08-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_n_air', '0005_rename_buys_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
