# Generated by Django 5.1 on 2024-08-30 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_n_air', '0008_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='last_name',
            new_name='Lastname',
        ),
    ]
