# Generated by Django 5.1 on 2024-09-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_n_air', '0009_rename_last_name_register_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('Lastname', models.CharField(max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=32)),
                ('massege', models.TextField()),
            ],
        ),
    ]
